README updates: Wording updates as per suggested in PR #7 review
datopian/frictionless-ckan-mapper-js pull request #8
Opened 2020-09-04 16:06 UTC by kmanaseryan

# Description

Made some updates in README related to wording as suggested in #7. 

Refs #7

2020-09-04 16:08 UTC, kmanaseryan commented
@rufuspollock whenever you get time please review this and merge if it looks good. Just made some small changes in README as per your comments in #7 PR.

2020-09-14 17:12 UTC, rufuspollock requested changes
i think a few misunderstandings that need correction.

2020-09-14 17:12 UTC, rufuspollock commented on README.md
> +const frictionlessDataset = {
this is a resource not a dataset ...

2020-09-14 17:12 UTC, rufuspollock commented on README.md
> +const ckanDataset = mapper.resourceFrictionlessToCkan(frictionlessDataset)
the output is a resource not a dataset i think ...

2020-09-14 17:12 UTC, rufuspollock commented on README.md
> +const ckanPackage = mapper.packageFrictionlessToCkan(frictionlessPackage)
I would consistently use the terminology dataset rather than package.

2020-09-14 17:12 UTC, rufuspollock commented on README.md
> +const ckanDataset = {
ditto to previous comment.

2020-09-16 12:44 UTC, merged